/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('@/components/Icon/index.ts')['default']
    'IconDataIcons.data': typeof import('@/components/Icon/data/icons.data.ts')['default']
    IconsIconCommunity: typeof import('@/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('@/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('@/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('@/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('@/components/icons/IconTooling.vue')['default']
    IconSrcIcon: typeof import('@/Icon.vue')['default']
    IconSrcIconPicker: typeof import('@/IconPicker.vue')['default']
    IconSrcSvgIcon: typeof import('@/SvgIcon.vue')['default']
    Loading: typeof import('@/components/Loading/index.ts')['default']
    LoadingSrcCreateLoading: typeof import('@/createLoading.ts')['default']
    LoadingSrcLoading: typeof import('@/Loading.vue')['default']
    LoadingSrcTyping: typeof import('@/typing.ts')['default']
    LoadingSrcUseLoading: typeof import('@/useLoading.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
