/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FieldInput: typeof import('@/components/FieldInput/index.ts')['default']
    FieldInputSrcFieldInput: typeof import('@/FieldInput.vue')['default']
    Icon: typeof import('@/components/Icon/index.ts')['default']
    'IconDataIcons.data': typeof import('@/components/Icon/data/icons.data.ts')['default']
    IconSrcIcon: typeof import('@/Icon.vue')['default']
    IconSrcSvgIcon: typeof import('@/SvgIcon.vue')['default']
    Loading: typeof import('@/components/Loading/index.ts')['default']
    LoadingSrcCreateLoading: typeof import('@/createLoading.ts')['default']
    LoadingSrcLoading: typeof import('@/Loading.vue')['default']
    LoadingSrcTyping: typeof import('@/typing.ts')['default']
    LoadingSrcUseLoading: typeof import('@/useLoading.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
